AWSTemplateFormatVersion: 2010-09-09
Description: >-
  covidspy-serverless
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 3
    MemorySize: 2048
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'*'"

Resources:
  GetSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/summary.handler
      Description: Returns a distinct list of all locations
      Events:
        SummaryApi:
          Type: Api
          Properties:
            RestApiId: !Ref CovidSpyApi
            Path: /api/summary
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: global_data
      Environment:
        Variables:
          TABLE_NAME: global_data
  
  GeTimeseriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/time-series.handler
      Description: Returns timeseries data for the specified location or the world
      Events:
        TimeseriesApi:
          Type: Api
          Properties:
            RestApiId: !Ref CovidSpyApi
            Path: /api/time-series
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: global_data
      Environment:
        Variables:
          TABLE_NAME: global_data

  GetTableDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/table-data.handler
      Description: Returns tabular data for currently selected location
      Events:
        TimeseriesApi:
          Type: Api
          Properties:
            RestApiId: !Ref CovidSpyApi
            Path: /api/table-data
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: global_data
      Environment:
        Variables:
          TABLE_NAME: global_data
  
  GetLocationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/locations.handler
      Description: Returns a distinct list of all locations
      Events:
        LocationsApi:
          Type: Api
          Properties:
            RestApiId: !Ref CovidSpyApi
            Path: /api/locations
            Method: GET
  CovidSpyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CovidSpy Api
      StageName: prod